#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php'; 
 
use Symfony\Component\Console\Application; 
use Payroll\PayrollCommand;


$app = new Application();

$app->add(new PayrollCommand());

$app->run();
